version: '3'

services:
  db:
  #  command: docker build -t products_db .
    image: products_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"

    volumes:
      - db-volume:/var/lib/mysql

volumes:
  db-volume: