version: '3'

services:
  db:
  #  command: docker build -t products_db .
    image: products_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"

    volumes:
      - db-volume:/var/lib/mysql

  server:
    container_name: server
    build: ./server
    image: api-server
    ports:
      - "3001:3001"
    command: npm start
    depends_on:
      - db
    environment:
      APP_PORT: 3001
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: db
      DB_PORT: 3306

volumes:
  db-volume: